version: '3.1'

services:
  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_HOST: mongo
      secret_key: asdniwbriuh23
    ports:
      - 8000:5050

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongov:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8787:8081
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
volumes:
  mongov:
